




CREATE DATABASE data_ucb


USE data_ucb

CREATE TABLE ARTISTA(
ID          INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
NOMBRE      VARCHAR(100)NOT NULL,
EDAD        INT NOT NULL,
TELEFONO    INT NOT NULL,
);

INSERT INTO ARTISTA(NOMBRE, EDAD, TELEFONO)
VALUES('DUA LIPA', 23, 62172405)

CREATE TABLE CONTRATO(
ID           INT IDENTITY (1,1) NOT NULL PRIMARY KEY,  
FECHA_INICIO DATETIME NOT NULL,
FECHA_FIN    DATETIME NOT NULL,
ID_ARTISTA   INT NOT NULL FOREIGN KEY REFERENCES ARTISTA(ID)
);

INSERT INTO CONTRATO(FECHA_INICIO, FECHA_FIN, ID_ARTISTA)
VALUES(GETDATE(), GETDATE()+10, 1)

CREATE TABLE CONCIERTO(
ID           INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
CAPACIDAD    INT NOT NULL,
DURACION     INT NOT NULL,
LUGAR        VARCHAR(200)NOT NULL,
ID_ARTISTA   INT NOT NULL FOREIGN KEY REFERENCES ARTISTA(ID)
);

INSERT INTO CONCIERTO(CAPACIDAD, DURACION, LUGAR, ID_ARTISTA)
VALUES(3, 8, 1, 1)

SELECT * FROM ARTISTA 
SELECT * FROM CONCIERTO
SELECT * FROM CONTRATO